service: team_retro
image: aronwolf/team-retro

servers:
  web:
    - 62.238.15.241

proxy:
  ssl: true
  host: retro.webcloudpower.com

registry:
  username: aronwolf
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - TEAM_PASSWORD
  clear:
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "team_retro_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64
<% if ENV["GITHUB_ACTIONS"] %>
  cache:
    type: gha
    options: mode=max
<% end %>
